name: 'Install packages'
description: 'Install listed packages using brew or apt'

inputs:
  packages:
    description: 'List of package names'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.packages }}

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        requested_packages="$(echo "${{ inputs.packages }}" \
          | sed 's/[[:space:]]\+/\n/g' | sed '/^$/d' | tr '\n' ' ')"
        echo \
          "Requested packages: $requested_packages"

        installed_packages="$(brew list | tr '\n' ' ')"
        echo \
          "Installed packages: $installed_packages"

        missing_packages="$(echo "$requested_packages" | tr ' ' '\n' \
          | ( grep -v -f <(echo "$installed_packages" | tr ' ' '\n') || true ) \
          | tr '\n' ' ')"
        echo \
          "Missing packages: "$missing_packages"

        if [[ ! -z "${missing_packages// }" ]]; then
          set -x
          brew install $missing_packages
        else
          echo "All requested packages already installed"
        fi
