name: 'Install packages'
description: 'Install listed packages using brew or apt'

inputs:
  packages:
    description: 'List of package names'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -x
        sudo apt-get update
        echo "${{ inputs.packages }}" | tr -s '[:space:]' ' ' \
          | xargs sudo apt-get install -y

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        requested_packages="$(echo "${{ inputs.packages }}" \
          | sed 's/[[:space:]]\+/\n/g' | sed '/^$/d' | tr '\n' ' ')"
        echo \
          "Requested packages: $requested_packages" 1>&2

        installed_packages="$(brew list | tr '\n' ' ')"
        echo \
          "Installed packages: $installed_packages" 1>&2

        missing_packages="$(echo "$requested_packages" | tr ' ' '\n' \
          | ( grep -v -x -f <(echo "$installed_packages" | tr ' ' '\n') || true ) \
          | tr '\n' ' ')"
        echo \
          "Missing packages: $missing_packages" 1>&2

        if [[ ! -z "${missing_packages// }" ]]; then
          set -x
          brew install $missing_packages
        else
          echo "All requested packages already installed"
        fi
