name: 'Post comment'
description: 'Post comment on issue or pull request'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  repo:
    description: 'Repo full name in form <org>/<repo>'
    required: true
  number:
    description: 'Issue or pull request number, or space-separated list of numbers'
    required: true
  text:
    description: 'Comment text'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
