name: 'Update project and status'
description: 'Update project and status of issue or pull request'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  number:
    description: 'Issue or pull request number, or list of numbers'
    required: true
  project:
    description: 'Project number'
    required: true
  status:
    description: 'Optional status in project'
    required: false
outputs:
  updated:
    description: "List of issue or pull request numbers that were updated"

runs:
  using: 'node20'
  main: 'dist/index.js'
