name: 'Docker run'
description: 'Run command in docker'

inputs:
  image:
    description: 'Docker image name'
    required: true
  run:
    description: 'Command to run'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        image: ${{ inputs.image }}
        command: ${{ inputs.run }}
      run: |
        docker run --rm -t \
          --cap-add SYS_PTRACE \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v ${{ github.workspace }}:/work \
          -w /work \
          -e CI="${CI:-}" \
          "${image}" \
          /bin/bash -c "${command}"
