name: 'Trigger dispatch event'
description: 'Send specified dispatch event to a repo'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  repo:
    description: 'Space-separated list of repo full names in form <org>/<repo>'
    required: true
  event:
    description: 'Event name'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        token="$(echo "${{ inputs.token }}" | tr -d '[:space:]')"
        event="$(echo "${{ inputs.event }}" | tr -d '[:space:]')"
        repos="$(echo "${{ inputs.repo }}" | tr -s '[:space:]' '\n')"

        echo "${repos}" \
          | while read repo; do
          echo "sending ${event} event to ${repo} ..."
          curl -Ls --fail-with-body -X POST \
            -H "Authorization: Bearer ${token}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            --data "{\"event_type\": \"${event}\", \"client_payload\": {}}" \
            "https://api.github.com/repos/${repo}/dispatches"
        done
