name: 'Issue info'
description: 'Fetch issue information using rgh.py'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  repo:
    description: 'Repo full name in form <org>/<repo>'
    required: true
  number:
    description: 'Issue number'
    required: true

outputs:
  info:
    description: 'Issue information in JSON'
    value: ${{ steps.rgh.outputs.info }}

runs:
  using: 'composite'
  steps:
    - id: rgh
      shell: bash
      run: |
        set -e
        info="$(${{ github.action_path }}/../../scripts/rgh.py show_issue --json \
          --repo ${{ inputs.repo }} ${{ inputs.number }})"
        echo "${info}" | jq -C .
        echo "info=${info}" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}
