name: "auto_project"

on:
  repository_dispatch:
    types:
      - issue_opened
      - issue_reopened
      - issue_labeled

jobs:
  setup:
    outputs:
      automation-config: ${{ steps.automation-config.outputs.config }}

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/automation-config@main
        id: automation-config
        with:
          repo: ${{ github.event.client_payload.repo }}
          github-token: ${{ secrets.BOT_TOKEN }}

  work:
    needs: setup
    if: |
      fromJson(needs.setup.outputs.automation-config).auto_project != null

    runs-on: ubuntu-latest
    steps:
      # assign project when issue is created
      - if: |
          github.event.name != 'issue_labeled'
        uses: roc-streaming/ci/actions/update-project@main
        with:
          repo: ${{ github.event.client_payload.repo }}
          number: ${{ github.event.client_payload.number }}
          project: ${{ fromJSON(needs.setup.outputs.automation-config).auto_project.project_id }}
          github-token: ${{ secrets.BOT_TOKEN }}

      # assign project column (status) based on issue labels
      - if: |
          github.event.name == 'issue_labeled' &&
          fromJSON(needs.setup.outputs.automation-config).auto_project.label_to_column != null
        uses: roc-streaming/ci/actions/update-project@main
        with:
          repo: ${{ github.event.client_payload.repo }}
          number: ${{ github.event.client_payload.number }}
          project: ${{ fromJSON(steps.automation-config.outputs.info).auto_project.project_id }}
          label-to-status: |
            ${{ toJSON(fromJSON(needs.setup.outputs.automation-config).auto_project.label_to_column) }}
          github-token: ${{ secrets.BOT_TOKEN }}
