name: "detect_stalled"

on:
  workflow_call:
    inputs:
      pr-stale-days:
        type: string
        required: true
      pr-close-days:
        type: string
        required: true
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  stale-pull-requests:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-label: "status: stalled"
          stale-pr-message: ":robot: Pull request is automatically marked as stalled
            because it has been open ${{ inputs.pr-stale-days }} days with no activity."
          close-pr-message: ":robot: Pull request is automatically closed
            because it has been open ${{ inputs.pr-close-days }} days with no activity."
          days-before-stale: ${{ inputs.pr-stale-days }}
          days-before-close: ${{ inputs.pr-close-days }}
          remove-stale-when-updated: true
          repo-token: ${{ secrets.triage-token }}
