name: "detect_conflicts"

on:
  workflow_call:
    inputs:
      development-branch:
        type: string
        default: "main"
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  detect-conflicts:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/detect-conflicts@main
        id: pr-statuses
        with:
          github-token: ${{ secrets.triage-token }}

      - if: |
          steps.pr-statuses.outputs.without-conflicts != '[]'
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: |
            ${{ join(fromJson(steps.pr-statuses.outputs.without-conflicts), ' ') }}
          remove-labels: |
            status: needs rebase
          github-token: ${{ secrets.triage-token }}

      - if: |
          steps.pr-statuses.outputs.with-conflicts != '[]'
        uses: roc-streaming/ci/actions/update-labels@main
        id: add-labels
        with:
          number: |
            ${{ join(fromJson(steps.pr-statuses.outputs.with-conflicts), ' ') }}
          add-labels: |
            status: needs rebase
          github-token: ${{ secrets.triage-token }}

      - if: |
          steps.add-labels.outputs.updated != '[]'
        uses: roc-streaming/ci/actions/post-comment@main
        with:
          number: |
            ${{ join(fromJson(steps.add-labels.outputs.updated), ' ') }}
          text: ":robot: Pull request is currently unmergeable due to conflicts.
            \n
            Please rebase on fresh `${{ inputs.development-branch }}` branch, resolve merge conflicts,
            and force-push to pull request's branch.
            Remember to use rebase with force-push instead of regular merge."
          github-token: ${{ secrets.triage-token }}
