name: "pr_detect_conflicts"

on:
  workflow_call:
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  gather-statuses:
    runs-on: ubuntu-latest
    outputs:
      with-conflicts: ${{ steps.pr-statuses.outputs.with-conflicts }}
      without-conflicts: ${{ steps.pr-statuses.outputs.without-conflicts }}

    steps:
      - uses: roc-streaming/ci/actions/detect-conflicts@main
        id: pr-statuses
        with:
          github-token: ${{ secrets.triage-token }}

  add-labels:
    runs-on: ubuntu-latest
    needs: [gather-statuses]
    if: |
      needs.gather-statuses.outputs.with-conflicts != '[]'
    strategy:
      matrix:
        pr-number: ${{ fromJson(needs.gather-statuses.outputs.with-conflicts) }}

    steps:
      - uses: roc-streaming/ci/actions/pullreq-info@main
        id: pr-info
        with:
          number: ${{ matrix.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          !contains(fromJson(steps.pr-info.outputs.info).pull_request.labels, 'status: needs rebase')
        uses: roc-streaming/ci/actions/post-comment@main
        with:
          number: ${{ matrix.pr-number }}
          text: ":robot: Pull request is currently unmergeable due to conflicts.
            \n
            Please rebase on fresh `${{ inputs.base-branch }}` branch, resolve merge conflicts,
            and force-push to pull request's branch.
            Remember to use rebase with force-push instead of regular merge."
          github-token: ${{ secrets.triage-token }}

      - if: |
          !contains(fromJson(steps.pr-info.outputs.info).pull_request.labels, 'status: needs rebase')
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ matrix.pr-number }}
          add-labels: |
            status: needs rebase
          github-token: ${{ secrets.triage-token }}

  remove-labels:
    runs-on: ubuntu-latest
    needs: [gather-statuses]
    if: |
      needs.gather-statuses.outputs.without-conflicts != '[]'
    strategy:
      matrix:
        pr-number: ${{ fromJson(needs.gather-statuses.outputs.without-conflicts) }}

    steps:
      - uses: roc-streaming/ci/actions/pullreq-info@main
        id: pr-info
        with:
          number: ${{ matrix.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          contains(fromJson(steps.pr-info.outputs.info).pull_request.labels, 'status: needs rebase')
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ matrix.pr-number }}
          remove-labels: |
            status: needs rebase
          github-token: ${{ secrets.triage-token }}
