name: "pr_detect_contrib"

on:
  workflow_call:
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/ci
          path: ci

      - name: Collect info
        id: pr-info
        run: |
          echo info="$(ci/scripts/rgh.py show_pr --json --repo ${{ github.repository }} \
              ${{ github.event.pull_request.number }})" >> "$GITHUB_OUTPUT"
        env:
         GH_TOKEN: ${{ secrets.triage-token }}

      - name: Add label
        if: |
          fromJson(steps.pr-info.outputs.info).pull_request.contrib == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            contribution
          github_token: ${{ secrets.triage-token }}
