name: "pr_detect_linked_issue"

on:
  workflow_call:
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/ci
          path: ci

      - name: Collect info
        id: pr-info
        run: |
          echo info="$(ci/scripts/rgh.py show_pr --json --repo ${{ github.repository }} \
              ${{ github.event.pull_request.number }})" >> "$GITHUB_OUTPUT"
        env:
         GH_TOKEN: ${{ secrets.triage-token }}

      - name: Post comment
        if: |
          fromJson(steps.pr-info.outputs.info).issue.url == '' ||
          fromJson(steps.pr-info.outputs.info).issue.url == 'null'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ":robot: Pull request description does not have a link to an issue.
            \n
            If there is a related issue, please add it to the description
            using any of the [supported formats](https://docs.github.com/en/get-started/\
            writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)."
          github-token: ${{ secrets.triage-token }}
