name: "pr_handle_ready"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            status: work in progress
            status: needs revision
          number: ${{ inputs.pr-number }}
          github_token: ${{ secrets.triage-token }}

      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            status: ready for review
          number: ${{ inputs.pr-number }}
          github_token: ${{ secrets.triage-token }}
