name: "pr_handle_closed"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ inputs.pr-number }}
          remove-labels: |
            status: work in progress
            status: ready for review
            status: review in progress
            status: needs revision
            status: needs rebase
          github-token: ${{ secrets.triage-token }}
