name: "pr_handle_closed"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            status: work in progress
            status: ready for review
            status: review in progress
            status: needs revision
            status: needs rebase
          number: ${{ inputs.pr-number }}
          github_token: ${{ secrets.triage-token }}
