name: "pr_handle_reviewed"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/pullreq-info@main
        id: pr-info
        with:
          number: ${{ inputs.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).review.decision == 'approved'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            status: ready for review
            status: needs revision
            status: review in progress
          number: ${{ inputs.pr-number }}
          github_token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).review.decision == 'changes_requested'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            status: ready for review
            status: work in progress
          number: ${{ inputs.pr-number }}
          github_token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).review.decision == 'changes_requested'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            status: needs revision
          number: ${{ inputs.pr-number }}
          github_token: ${{ secrets.triage-token }}
