name: "pr_lint_linked_issue"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  lint-linked-issue:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/pullreq-info@main
        id: pr-info
        with:
          number: ${{ inputs.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).linked_issue == null
        uses: roc-streaming/ci/actions/post-comment@main
        with:
          number: ${{ inputs.pr-number }}
          text: ":robot: Pull request description does not have a link to an issue.
            \n
            If there is a related issue, please add it to the description
            using any of the [supported formats](https://docs.github.com/en/get-started/\
            writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)."
          github-token: ${{ secrets.triage-token }}
