name: "pr_status_needs_revision"

on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            status: ready for review
            status: work in progress

      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            status: needs revision
