name: "pr_status_wip"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  set-status-wip:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/pullreq-info@main
        id: pr-info
        with:
          number: ${{ inputs.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).pull_request.is_draft == true ||
          fromJson(steps.pr-info.outputs.info).review.requested == false
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ inputs.pr-number }}
          remove-labels: |
            status: ready for review
            status: needs revision
          add-labels: |
            status: work in progress
          github-token: ${{ secrets.triage-token }}
