name: "pr_status_opened"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write
  checks: read

jobs:
  set-status-opened:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/wait-checks@main
        id: pr-info
        with:
          workflow: "build"
          number: ${{ inputs.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - uses: roc-streaming/ci/actions/pullreq-info@main
        id: pr-info
        with:
          number: ${{ inputs.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).actions.build == 'failure' &&
          !contains(toJson(fromJson(steps.pr-info.outputs.info).labels), 'status:')
        uses: roc-streaming/ci/actions/post-comment@main
        with:
          number: ${{ inputs.pr-number }}
          text: ":robot: Pull request has failed checks and was automatically marked as
            work-in-progress.
            \n
            If you believe the failures are unrelated or you want an early review, click on
            the `request review` button. Otherwise, please fix failures before requesting review."
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).pull_request.is_draft == true ||
          (fromJson(steps.pr-info.outputs.info).actions.build == 'failure' &&
           !contains(toJson(fromJson(steps.pr-info.outputs.info).labels), 'status:'))
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ inputs.pr-number }}
          add-labels: |
            status: work in progress
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).review.requested == true ||
          (fromJson(steps.pr-info.outputs.info).actions.build == 'success' &&
           !contains(toJson(fromJson(steps.pr-info.outputs.info).labels), 'status:'))
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ inputs.pr-number }}
          add-labels: |
            status: ready for review
          github-token: ${{ secrets.triage-token }}
