name: "pr_status_reviewed"

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: number
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write

jobs:
  set-status-reviewed:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/pullreq-info@main
        id: pr-info
        with:
          number: ${{ inputs.pr-number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).review.decision == 'approved'
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ inputs.pr-number }}
          remove-labels: |
            status: ready for review
            status: review in progress
            status: needs revision
          github-token: ${{ secrets.triage-token }}

      - if: |
          fromJson(steps.pr-info.outputs.info).review.decision == 'changes_requested'
        uses: roc-streaming/ci/actions/update-labels@main
        with:
          number: ${{ inputs.pr-number }}
          remove-labels: |
            status: ready for review
            status: work in progress
          add-labels: |
            status: needs revision
          github-token: ${{ secrets.triage-token }}
