name: "project_assign"

on:
  workflow_call:
    inputs:
      number:
        required: true
        type: number
      project:
        type: string
        required: true
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write
  issues: write

jobs:
  assign-project:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/update-project@main
        with:
          number: ${{ inputs.number }}
          project: ${{ inputs.project }}
          github-token: ${{ secrets.triage-token }}
