name: "project_assign_column"

on:
  workflow_call:
    inputs:
      number:
        required: true
        type: number
      project:
        type: string
        required: true
      if-labeled:
        type: string
        required: true
      set-column:
        type: string
        required: true
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write
  issues: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/actions/issue-info@main
        id: issue-info
        with:
          number: ${{ inputs.number }}
          github-token: ${{ secrets.triage-token }}

      - if: |
          contains(fromJson(steps.issue-info.outputs.info).issue.labels, ${{ inputs.if-labeled }})
        uses: roc-streaming/ci/actions/update-project@main
        with:
          number: ${{ inputs.number }}
          project: ${{ inputs.project }}
          status: ${{ inputs.set-column }}
          github-token: ${{ secrets.triage-token }}
