name: "project_assign"

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
    secrets:
      triage-token:
        required: true

permissions:
  pull-requests: write
  issues: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # add item for *current* issue to project
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: "https://github.com/orgs/roc-streaming/projects/${{ inputs.project }}"
          github-token: ${{ secrets.triage-token }}
