name: "trigger_build"

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      branch:
        type: string
        default: "main"
    secrets:
      ci-token:
        required: true

permissions:
  actions: write

jobs:
  trigger-build:
    if: |
      github.repository_owner == 'roc-streaming'

    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -Ls --fail-with-body -X POST \
            -H 'Authorization: Bearer ${{ secrets.ci-token }}' \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Content-Type: application/json' \
            'https://api.github.com/repos/roc-streaming/${{ inputs.repo }}/dispatches' \
            --data \
            '{"event_type": "trigger_build", "client_payload": {"branch": "${{ inputs.branch }}"}}'
